export const PLANS_DATA = [
  {
    plan: "Start",
    description:
      "Para quienes están dando sus primeros pasos y necesitan herramientas clave para comenzar a construir una gestión de personas efectiva.",
    price: "USD 149/mes",
    includes: [
      "110 créditos de búsqueda de talento (1 vacante entry level/mes)",
      "2 horas de consultoría mensual",
      "1 mentoría grupal + 1 curso mensual en Uplin Academy",
      "Charlas ilimitadas en Uplin Academy",
      "Soporte por email y WhatsApp",
      "Acceso a comunidad exclusiva Uplin",
      "HR Advisor dedicado",
    ],
    excludes: ["Créditos acumulables", "Auditoría de talento"],
    showTaxes: true,
    link: "https://u030x.share.hsforms.com/286X_JYW8RMe3xqoRYdv0BQ",
  },
  {
    plan: "Growth",
    description:
      "Pensado para líderes que quieren fortalecer sus procesos de talento y optimizar resultados en equipos en expansión.",
    price: "USD 499/mes",
    includes: [
      "120 créditos de búsqueda de talento (1 vacante junior/mes)",
      "Créditos acumulables hasta 3 meses",
      "4 horas de consultoría mensual",
      "1 mentoría grupal + 1 curso mensual en Uplin Academy",
      "Charlas ilimitadas en Uplin Academy",
      "Soporte por email y WhatsApp",
      "Acceso a comunidad exclusiva Uplin",
      "HR Advisor dedicado",
    ],
    excludes: ["Auditoría de talento"],
    showTaxes: true,
    link: "https://u030x.share.hsforms.com/2YbIGCcG1QKeQfvlPkDXaAg",
  },
  {
    plan: "Premium",
    description:
      "Ideal para organizaciones que buscan crecer con estrategia, profesionalizar sus procesos y maximizar su impacto.",
    price: "USD 1399/mes",
    includes: [
      "300 créditos de búsqueda de talento (1 vacante C-level/mes o combinación de perfiles)",
      "Créditos acumulables hasta 3 meses",
      "8 horas de consultoría mensual",
      "1 mentoría grupal + 1 curso mensual en Uplin Academy",
      "Charlas ilimitadas en Uplin Academy",
      "Soporte por email y WhatsApp",
      "Acceso a comunidad exclusiva Uplin",
      "HR Advisor dedicado",
      "Auditoría de talento",
    ],
    excludes: [],
    showTaxes: true,
    link: "https://u030x.share.hsforms.com/2RzcQoh4pRnKgh-FbBmKt2Q",
  },
  {
    plan: "Custom",
    description:
      "Armamos tu plan con los servicios que necesitás para proyectos específicos, desafíos puntuales o procesos estratégicos.",
    price: "A convenir",
    includes: [
      "Créditos de búsqueda de talento a medida",
      "Horas de consultoría personalizadas",
      "Membresía a Uplin Academy (1 mentoría grupal mensual + 1 curso mensual + charlas ilimitadas)",
      "Soporte por email y WhatsApp",
      "Acceso a comunidad exclusiva Uplin",
      "HR Advisor dedicado",
      "Auditoría del área de talento",
    ],
    excludes: [],
    showTaxes: false,
    isCustom: true,
    link: "https://u030x.share.hsforms.com/2C4ee9yIoQr6AXMTrRwS8QQ",
  },
];
